config/routes.rb
SampleApp::Application.routes.draw do

  resources :user_items

  resources :defalut_items

  resources :stores

  resources :items

  resources :users do
    member do
    end
  end

  
  resources :comments,    :only => [:create, :destroy, :new, :show]
  
 root :to => "items#index"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/home', :to => 'pages#home'

 

end

app/models/defalut_item.rb
class DefalutItem < ActiveRecord::Base
end

app/controllers/defalut_items_controller.rb
class DefalutItemsController < ApplicationController
  # GET /defalut_items
  # GET /defalut_items.xml
  def index
    @defalut_items = DefalutItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @defalut_items }
    end
  end

  # GET /defalut_items/1
  # GET /defalut_items/1.xml
  def show
    @defalut_item = DefalutItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @defalut_item }
    end
  end

  # GET /defalut_items/new
  # GET /defalut_items/new.xml
  def new
    @defalut_item = DefalutItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @defalut_item }
    end
  end

  # GET /defalut_items/1/edit
  def edit
    @defalut_item = DefalutItem.find(params[:id])
  end

  # POST /defalut_items
  # POST /defalut_items.xml
  def create
    @defalut_item = DefalutItem.new(params[:defalut_item])

    respond_to do |format|
      if @defalut_item.save
        format.html { redirect_to(@defalut_item, :notice => 'Defalut item was successfully created.') }
        format.xml  { render :xml => @defalut_item, :status => :created, :location => @defalut_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @defalut_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /defalut_items/1
  # PUT /defalut_items/1.xml
  def update
    @defalut_item = DefalutItem.find(params[:id])

    respond_to do |format|
      if @defalut_item.update_attributes(params[:defalut_item])
        format.html { redirect_to(@defalut_item, :notice => 'Defalut item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @defalut_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /defalut_items/1
  # DELETE /defalut_items/1.xml
  def destroy
    @defalut_item = DefalutItem.find(params[:id])
    @defalut_item.destroy

    respond_to do |format|
      format.html { redirect_to(defalut_items_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/defalut_items_helper.rb
module DefalutItemsHelper
end

app/views/defalut_items/_form.html.erb
<%= form_for(@defalut_item) do |f| %>
  <% if @defalut_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@defalut_item.errors.count, "error") %> prohibited this defalut_item from being saved:</h2>

      <ul>
      <% @defalut_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br />
    <%= f.text_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :qty %><br />
    <%= f.text_field :qty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/defalut_items/edit.html.erb
<h1>Editing defalut_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @defalut_item %> |
<%= link_to 'Back', defalut_items_path %>

app/views/defalut_items/index.html.erb
<h1>Listing defalut_items</h1>

<table>
  <tr>
    <th>Item</th>
    <th>Qty</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @defalut_items.each do |defalut_item| %>
  <tr>
    <td><%= defalut_item.item_id %></td>
    <td><%= defalut_item.qty %></td>
    <td><%= link_to 'Show', defalut_item %></td>
    <td><%= link_to 'Edit', edit_defalut_item_path(defalut_item) %></td>
    <td><%= link_to 'Destroy', defalut_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Defalut item', new_defalut_item_path %>

app/views/defalut_items/new.html.erb
<h1>New defalut_item</h1>

<%= render 'form' %>

<%= link_to 'Back', defalut_items_path %>

app/views/defalut_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Item:</b>
  <%= @defalut_item.item_id %>
</p>

<p>
  <b>Qty:</b>
  <%= @defalut_item.qty %>
</p>


<%= link_to 'Edit', edit_defalut_item_path(@defalut_item) %> |
<%= link_to 'Back', defalut_items_path %>