config/routes.rb
SampleApp::Application.routes.draw do

  resources :user_items

  resources :defalut_items

  resources :stores

  resources :items

  resources :users do
    member do
    end
  end

  
  resources :comments,    :only => [:create, :destroy, :new, :show]
  
 root :to => "items#index"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/home', :to => 'pages#home'

 

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul id="nav">
      <li>@copyright 2011</li>
      <li>&nbsp&nbsp</li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<%#= link_to logo, root_path %>
<%#= image_tag("awlogo4.gif", :size=>"663x75") %>
  <!--<%= link_to image_tag("logo1.jpeg", :size=>"100x50"), root_path %> -->
  <head>
  <div class="round" style="margin-top:10px;background-color: #eeeeee;float:right;width:100%;height:2px;">
    <% if signed_in? %>
      <span style="float:right;margin-right:10px;margin-top:40px;">
        Welcome <%=current_user.email%>&nbsp;|&nbsp;<%= link_to "Sign out", signout_path %>
      </span>
    <% end %>
  </div>
</head>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]--><%= stylesheet_link_tag "default" %>
    <%= stylesheet_link_tag 'south-street/jquery-ui-1.8.4.custom' %>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Cabin:bold' %>
     <%= javascript_include_tag 'application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body class="<%= @body %>">
     <%= link_to image_tag("melogo12.gif",:style =>"width:100%;", :alt =>"milkeggs"), root_path %>
     <%= link_to image_tag("melogo_words.gif",:style =>"width:100%;", :alt =>"milkeggs"), root_path %>
    <div id="header-wrap">
      <%= render 'layouts/header' %>
           <ul id="nav">
             <p class="welcome">
                <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "Items", root_path %></li>
             <li><%= link_to "Stores", stores_path %></li>
              <li><%= link_to "Def.Items", defalut_items_path %></li>
              <li><%= link_to "Users", users_path %></li>
              <% if signed_in? %>
                  <% if false%>
                     <li><%= link_to "Retirees", retiree_path %></li>
                    <li> <%= link_to "Profile", current_user %> </li>
                    <li><%= link_to "Users", users_path %></li>
                    <li><%=link_to "Moderate Comments", comments_path  if current_user.admin? %></li>
                  <% end %>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <% end %>
          </p>
          </ul>
        </nav>
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
         <%= render 'layouts/footer' %>
          <br />
           <br />
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>